# .github/workflows/terraform-check.yml
name: Terraform Format and Validate

on:
  pull_request:
    branches: [main, dev] # Customize as needed

jobs:
  terraform-check:
    name: Terraform Format and Validate
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6  # Use your project's version

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Initialize Terraform
      run: terraform init -backend=false

    - name: Terraform Validate
      run: terraform validate
